version: "3"

services:
  api:
    build: ./api
    ports:
      - "5000:9090"
    depends_on:
      - postgres
    links:
      - postgres:db
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 3x4mpl3